services:
  - type: web
    name: smart-medical-store-backend
    runtime: node
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: FRONTEND_ORIGINS
        value: "https://darling-kringle-1b928d.netlify.app"